2019-07-03 21:15:11 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.jianshu.com/p/3c15af34c5a3> (referer: https://www.jianshu.com/p/fc1c113e5b6b)
Traceback (most recent call last):
  File "/home/zhou/.virtualenvs/scrapy-spider/lib/python3.7/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/home/zhou/.virtualenvs/scrapy-spider/lib/python3.7/site-packages/scrapy/spidermiddlewares/offsite.py", line 29, in process_spider_output
    for x in result:
  File "/home/zhou/.virtualenvs/scrapy-spider/lib/python3.7/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/home/zhou/.virtualenvs/scrapy-spider/lib/python3.7/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/zhou/.virtualenvs/scrapy-spider/lib/python3.7/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/home/zhou/.virtualenvs/scrapy-spider/lib/python3.7/site-packages/scrapy/spiders/crawl.py", line 78, in _parse_response
    for requests_or_item in iterate_spider_output(cb_res):
  File "/home/zhou/extend/scrapy-spider/jianshu/jianshu/spiders/js.py", line 26, in parse_detail
    item['pub_time'] = response.xpath("//span[@class='publish-time']/text()").get().replace('*','')
AttributeError: 'NoneType' object has no attribute 'replace'
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd51499438>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd514995f8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd51499588>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd51499748>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd51499828>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd51499470>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd514eceb8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd514ecd68>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd514ecda0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd514ecb70>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd50f08780>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd50f7c438>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5155c940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5155ccc0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5155c160>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5155c400>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd50f7c208>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515b0668>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515b0dd8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515b0828>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515b0eb8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5158cac8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5158c828>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5158ceb8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5158c978>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd5158c710>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515fc550>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515ebd30>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515ebfd0>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd515eb940>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd50f00eb8>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd50f00128>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
2019-07-03 21:15:37 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7efd50f00d68>: Failed to establish a new connection: [Errno 111] Connection refused')': /session/06e3dc2ce1587d2cc1c69a2bc292b4cd/url
